name: Build and Set Up Lambda
on: 
  push:
    branches: [main] 
  
jobs:
  my_job:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    env:
        REPOSITORY: ${{ secrets.REPO_NAME }}
        IMAGE_TAG: ${{ github.run_id }}
    steps:
    
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: us-east-1
            
    - name: Login to Amazon ECR Public
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, Tag, and Push the Image to Amazon ECR
      id: build-image
      env:
       REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        docker build -t $REGISTRY/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REPOSITORY:$IMAGE_TAG

    - name: Update Lambda Function
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
      run: |
        echo $REGISTRY
        aws lambda update-function-code --function-name git-hub-actions-lambda-fun --image-uri $REGISTRY/$REPOSITORY:$IMAGE_TAG 
